# Generated by Django 3.2 on 2021-04-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210411_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='url',
        ),
        migrations.AlterField(
            model_name='blogger',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
