# Generated by Django 3.2 on 2021-04-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='url',
        ),
    ]
