# Generated by Django 3.2 on 2021-04-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_blogger_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
